import { BarChart } from "@/components/BarChart";
import Header from "@/components/Header";
import RecentOrders from "@/components/RecentOrders";
import TopCards from "@/components/TopCards";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen">
        <div className="w-[95%] mx-auto">
          <Header />
          <TopCards />
          <div className="my-6 grid md:grid-cols-4 grid-cols-1 gap-4">
            <div className="col-span-2">
              <BarChart/>
            </div>
            <div className="col-span-2 bg-white w-full">
              <RecentOrders/>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
