import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import TextEditor from "@/components/TextEditor";

const newpost = () => {
  return (
    <>
      <Head>
        <title>New Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="w-[95%] mx-auto">
        <h1 className="text-xl font-bold text-gray-700 my-4">Add New Post</h1>
          <TextEditor/>
      </div>
    </>
  );
};

export default newpost;
