import React from "react";
import Head from "next/head";
import Header from "@/components/Header";

const newpost = () => {
  return (
    <>
      <Head>
        <title>New Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="w-[95%] mx-auto">
        <h1 className="text-xl font-bold text-gray-700 my-4">Add New Post</h1>
        <div className="grid grid-cols-4 gap-4">
          <div className="col-span-3">
            <div className="my-2">
              <input
                type="text"
                className="w-full border-[1px] border-gray-400 rounded-sm py-2 px-4 outline-none "
                placeholder="Enter title here"
              />
            </div>
            <div className=" my-2">
              <textarea
                name=""
                id=""
                className="w-full border-[1px] border-gray-400 rounded-sm py-2 px-4 outline-none "
                cols="30"
                rows="10"
              ></textarea>
            </div>
          </div>

          {/* side */}
          <div className="my-2">
            <div className="border-[1px] border-gray-400 rounded-sm p-2">
              <label
                for="countries"
                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >
                Select an option
              </label>
              <select
                id="countries"
                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              >
                <option selected>Public</option>
                <option value="US">Draft</option>
              </select>
            </div>
            <div>
             2
            </div>
            <div>3</div>
          </div>
        </div>
      </div>
    </>
  );
};

export default newpost;
